### ISSUE TITLE
cluster-autoscaler panics when newly launched instance type is used

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/autoscaler#53]
**What happened**:
Currently https://github.com/gardener/autoscaler/blob/machine-controller-manager/cluster-autoscaler/cloudprovider/azure/azure_instance_types.go is outdated compared to https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/azure_instance_types.go.
cluster-autoscaler panics when such instance type that is not present in `azure_instance_types.go` is used with scale-from-zero feature.

**What you expected to happen**:
https://github.com/gardener/autoscaler/blob/machine-controller-manager/cluster-autoscaler/cloudprovider/azure/azure_instance_types.go to be updated with newly launched instance types.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a worker pool with instance type that is not maintained in https://github.com/gardener/autoscaler/blob/machine-controller-manager/cluster-autoscaler/cloudprovider/azure/azure_instance_types.go (for example `Standard_D2d_v4`) and `minimum=0`

```yaml
  workers:
    # omitted
    - machine:
        image:
          name: coreos
          version: 2512.3.0
        type: Standard_D2d_v4
      maxSurge: 1
      maxUnavailable: 0
      maximum: 1
      minimum: 0
      name: cpu-worker2
      systemComponents:
        allow: true
      volume:
        size: 35Gi
        type: standard
```

2. Create a Pod that would trigger scale-up.

3. Ensure that cluster-autoscaler panics with:

```
$ k -n shoot--foo--bar logs cluster-autoscaler-78bc9675cb-scwvg

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3051428]

goroutine 90 [running]:
github.com/gardener/autoscaler/cluster-autoscaler/cloudprovider/mcm.(*McmManager).GetMachineDeploymentNodeTemplate(0xc420b70e10, 0xc420988bc0, 0x2, 0x0, 0xc4214caea0)
	/tmp/build/80754af9/git-gardener_autoscaler-machine-controller-manager_machine-controller-manager/tmp/src/github.com/gardener/autoscaler/cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:425 +0x508
github.com/gardener/autoscaler/cluster-autoscaler/cloudprovider/mcm.(*MachineDeployment).TemplateNodeInfo(0xc420988bc0, 0xc4214caea0, 0x7ffeffe95344, 0x28)
	/tmp/build/80754af9/git-gardener_autoscaler-machine-controller-manager_machine-controller-manager/tmp/src/github.com/gardener/autoscaler/cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go:349 +0x38
github.com/gardener/autoscaler/cluster-autoscaler/core.GetNodeInfosForGroups(0xc421455460, 0x2, 0x2, 0x44582a0, 0xc421076c00, 0x447e3a0, 0xc4209f4a00, 0x0, 0x0, 0x0, ...)
	/tmp/build/80754af9/git-gardener_autoscaler-machine-controller-manager_machine-controller-manager/tmp/src/github.com/gardener/autoscaler/cluster-autoscaler/core/utils.go:269 +0x296
github.com/gardener/autoscaler/cluster-autoscaler/core.ScaleUp(0xc4201b9860, 0xc420d38f00, 0xc420a5cf00, 0xc420b5f0d0, 0x1, 0x1, 0xc421455460, 0x2, 0x2, 0x0, ...)
	/tmp/build/80754af9/git-gardener_autoscaler-machine-controller-manager_machine-controller-manager/tmp/src/github.com/gardener/autoscaler/cluster-autoscaler/core/scale_up.go:267 +0x420
github.com/gardener/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0xc420b70ea0, 0xbfcab3e9d11cc4ae, 0x2590855617, 0x6b4cea0, 0x0, 0x0)
	/tmp/build/80754af9/git-gardener_autoscaler-machine-controller-manager_machine-controller-manager/tmp/src/github.com/gardener/autoscaler/cluster-autoscaler/core/static_autoscaler.go:273 +0x1e0c
main.run(0xc4206a4000)
	/tmp/build/80754af9/git-gardener_autoscaler-machine-controller-manager_machine-controller-manager/tmp/src/github.com/gardener/autoscaler/cluster-autoscaler/main.go:294 +0x1dd
main.main.func2(0x443ae00, 0xc420dc9bc0)
	/tmp/build/80754af9/git-gardener_autoscaler-machine-controller-manager_machine-controller-manager/tmp/src/github.com/gardener/autoscaler/cluster-autoscaler/main.go:373 +0x2a
created by github.com/gardener/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/tmp/build/80754af9/git-gardener_autoscaler-machine-controller-manager_machine-controller-manager/tmp/src/github.com/gardener/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:155 +0xee
```

```
$ k -n shoot--foo--bar get po -l role=cluster-autoscaler
NAME                                  READY   STATUS             RESTARTS   AGE
cluster-autoscaler-78bc9675cb-scwvg   0/1     CrashLoopBackOff   6          8m52s
```

**Anything else we need to know**:

**Environment**:

**Comment by hardikdr** [comment]
/assign
We need to update the supported machine types.
